/**
 * Default monster roles.
 */
const DEFAULT_ROLES = {
  controller: {
    id: "controller",
    ac: 2,
    hp: 0,
    damage: 1,
    dc: 0,
    xp: 1,
    perception: false,
    stealth: false,
    initiative: true,
  },
  defender: {
    id: "defender",
    ac: 4,
    hp: 0.75,
    damage: 0.75,
    dc: 0,
    xp: 1,
    perception: false,
    stealth: false,
    initiative: false,
  },
  lurker: {
    id: "lurker",
    ac: -4,
    hp: 0.75,
    damage: 1.25,
    dc: 2,
    xp: 1,
    perception: false,
    stealth: true,
    initiative: false,
  },
  skirmisher: {
    id: "skirmisher",
    ac: -2,
    hp: 0.75,
    damage: 1,
    dc: 0,
    xp: 1,
    perception: true,
    stealth: false,
    initiative: false,
  },
  striker: {
    id: "striker",
    ac: 1,
    hp: 1,
    damage: 1,
    dc: 2,
    xp: 1,
    perception: false,
    stealth: false,
    initiative: false,
  },
  supporter: {
    id: "supporter",
    ac: 1,
    hp: 1.25,
    damage: 0.75,
    dc: 0,
    xp: 1,
    perception: false,
    stealth: false,
    initiative: true,
  },
};

export default DEFAULT_ROLES;
